name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, 'feature/*' ]
  pull_request:
    branches: [ main, develop, 'feature/*' ]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      node-versions: '["18.x", "20.x"]'
  
  build:
    uses: ./.github/workflows/build.yml
    needs: test
    with:
      node-version: '18'
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy
      run: |
        echo "Add your deployment steps here"
        # Example deployment steps:
        # - Build Docker image
        # - Push to container registry
        # - Deploy to cloud platform
